using System.Text;

namespace Titan.Generators.Components;

internal static class ComponentBuilder
{
    public static string Build(in ComponentType component)
    {
        var builder = new FormattedBuilder(new StringBuilder());
        var type = component.Type;
        builder
            .AppendAutoGenerated()
            .AppendLine()
            .AppendLine($"namespace {type.ContainingNamespace.ToDisplayString()};")
            .AppendLine()
            .AppendLine($"{type.DeclaredAccessibility.AsString()} unsafe partial struct {type.Name} : {TitanTypes.IComponent}")
            .AppendOpenBracer()
            .AppendLine($"public static ComponentType Type {{get;}} = {TitanTypes.ComponentType}.GetNext<{type.Name}>();")
            .AppendCloseBracer();

        return builder.ToString();
    }
}
